### ISSUE TITLE
Is it possible to store data persistently?

### ISSUE THREAD

**Issue by subkitsupport** [subkit/help#23]

**Comment by MikeBild** [comment]
Yes. You can store data across different request/responses respectively runtime sandboxes into a key/value document oriented way. It's a CouchDB compatible HTTP-API and you can easily use the PouchDB API to dealing with your data. The Subkit store have a hard limit of 1MB per document.   

Based on a asynchron continuously replicated data object approach, you can also use Subkit's state object. This object is implemented as a proxy for document aggregate data manipulation operations.

** Additional Informations **
* [Introduction Subkit State Object](https://www.subkit.io/doc/#introduction-code-sandbox-api)
* [Using Subkit State Object](https://www.subkit.io/doc/#tutorial-state-object)
* [Using Subkit Store-API](https://www.subkit.io/doc/#tutorial-store-api)
* [PouchDB](http://pouchdb.com)
* [CouchDB](http://couchdb.apache.org)
* [Introduction to NoSQL by Martin Fowler](https://www.youtube.com/watch?v=qI_g07C_Q5I)
