### ISSUE TITLE
How do I organize larger applications?

### ISSUE THREAD

**Issue by subkitsupport** [subkit/help#24]

**Comment by MikeBild** [comment]
Subkit was designed to create larger applications from small independent parts. One way to doing this are the concepts of Microservice architectures. The most important principle is the decomposition of the business domain into small independently developable but composable parts. Every Subkit account is a representation of a consistency boundary preferably a bounded context. With this knowledge, it's close to create multiple accounts for different bounded contexts. Create multiple GitHub accounts that are connected to Subkit. This is our recommendation to allow independent development of parts of a larger application.
